name: Desplegar en EC2

on:
  workflow_dispatch:

jobs:
  despliegue_ec2:
    runs-on: ubuntu-latest
    steps:
      - name: 1.Checkout del cÃ³digo
        uses: actions/checkout@v4

      - name: 2. Copiar archivos a isntancia
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          source: "."
          target: "/home/${{ secrets.EC2_USER }}/site"   

      # 2) Ejecutar comandos remotos: mover a carpeta web y reiniciar nginx
      - name: Move files to web dir and restart nginx
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            sudo mkdir -p /var/www/my-site
            sudo cp -r /home/${{ secrets.EC2_USER }}/site/* /var/www/my-site/
            # permisos: prueba para Ubuntu/Nginx
            sudo chown -R www-data:www-data /var/www/my-site 2>/dev/null | true
            sudo systemctl restart nginx || true
