name: Comprobación pruebas unitarias

on:
  workflow_dispatch: #Ejecución cuando se le de al boton
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  comprobar_pruebas_unitarias:
    runs-on: ubuntu-latest

    steps: 
      - name: 1. Checkout del código
        uses: actions/checkout@v5

      - name: 2. Instalar dependencias
        run: npm install

      - name: 3. Arreglar permisos del binario Jest
        run: chmod +x ./node_modules/.bin/jest

      - name: 4. Ejecutar pruebas unitarias
        run: npm test
    
